### PR TITLE
balena-supervisor: Set imx8mm-lpddr4-evk LED for indication

### PR DESCRIPTION
**Pull request by ajlennon**
Changelog-entry: Set imx8mm-lpddr4-evk LED for indication

### CODE REVIEW

**Comment by ajlennon** [comment]
Checked this seems to flash the LED ok - can you merge please @floion ?

**Comment by acostach** [comment]
@resin-jenkins test this please

**Review by floion — APPROVED** [review]

**Comment by acostach** [comment]
@resin-jenkins ok to test

**Comment by acostach** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
Superseded by https://github.com/balena-os/balena-fsl-arm/pull/557

**Comment by floion** [comment]
@resin-jenkins test this please

**Review by floion — APPROVED** [review]

**Pull request merged**
